create table board
(
  tno bigint generated by default as identify,
  title varchar(255) ,
  content varchar(500) ,
  primary key (tno)
);
create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);
